### ISSUE TITLE
vue2版本打包的时候，会报错，请问要怎么解决

### ISSUE THREAD

**Issue by zzzzzero000** [xaboy/form-create-designer#133]
[!] Error: Could not resolve entry module (rollup.config.js).
Error: Could not resolve entry module (rollup.config.js).
    at error (D:\zero\project\form-create-designer\node_modules\rollup\dist\shared\rollup.js:198:30)
    at ModuleLoader.loadEntryModule (D:\zero\project\form-create-designer\node_modules\rollup\dist\shared\rollup.js:22306:20)   
    at async Promise.all (index 0)

**Comment by zzzzzero000** [comment]
在vue2版本基础上，对源码进行二次开发后，推到自己的库里，目前卡在打包这一步，求大佬帮忙看下哈
