### ISSUE TITLE
拖拽单选框点击时间row为空

### ISSUE THREAD

**Issue by guoziqin** [xaboy/form-create-designer#81]
Version： "@form-create/designer": "^3.1.3",
    "@form-create/element-ui": "^3.1.18",

**Comment by guoziqin** [comment]
拖拽多选框后单击多选框 也是有问题

**Comment by guoziqin** [comment]
原先的依赖版本是
"@form-create/designer": "^3.1.0",
 "@form-create/element-ui": "^3.1.17",

**Comment by guoziqin** [comment]
重新编译了下加了个判断

**Comment by guoziqin** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/37041136/230759997-4dfbf38e-470a-47fd-8ffc-60ed0c0b747a.png">
可以fix下么

**Comment by xaboy** [comment]
row为空? 没有明白是什么问题 @guoziqin

**Comment by BowenHero** [comment]
我也有这个问题  node18.3.0  npm9.6.3
index.es.js:11979 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'row')
    at index.es.js:11979:29
    at renderFnWithContext (runtime-core.esm-bundler.js:852:19)
    at normalizeChildren (runtime-core.esm-bundler.js:7006:42)
    at createBaseVNode (runtime-core.esm-bundler.js:6755:9)
    at _createVNode (runtime-core.esm-bundler.js:6857:12)
    at createVNodeWithArgsTransform (runtime-core.esm-bundler.js:6712:12)
    at createBlock (runtime-core.esm-bundler.js:6683:23)
    at index.es.js:11972:105
    at renderList (runtime-core.esm-bundler.js:2912:22)
    at index.es.js:11972:60
