### ISSUE TITLE
无法读取未定义的属性(读取'row')

### ISSUE THREAD

**Issue by BowenHero** [xaboy/form-create-designer#82]
node18.3.0 npm9.6.3
拖拽组件到中间幕布显示后，点击就会报错
index.es.js:11979 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'row')
at index.es.js:11979:29
at renderFnWithContext (runtime-core.esm-bundler.js:852:19)
at normalizeChildren (runtime-core.esm-bundler.js:7006:42)
at createBaseVNode (runtime-core.esm-bundler.js:6755:9)
at _createVNode (runtime-core.esm-bundler.js:6857:12)
at createVNodeWithArgsTransform (runtime-core.esm-bundler.js:6712:12)
at createBlock (runtime-core.esm-bundler.js:6683:23)
at index.es.js:11972:105
at renderList (runtime-core.esm-bundler.js:2912:22)
at index.es.js:11972:60

**Comment by BowenHero** [comment]
[
![image](https://user-images.githubusercontent.com/35329746/231115424-1d667140-225c-48a3-bf35-46db4a57defc.png)
](url)

**Comment by xaboy** [comment]
看一下 index.es.js:11979:29 文件对应位置的代码 @BowenHero

**Comment by BowenHero** [comment]
[
![9e6d339159d7cb0b0919f13aafc1b2f](https://user-images.githubusercontent.com/35329746/231362910-f0ca8127-a0c9-4d27-aafa-b6dc2d801748.png)
](url)

**Comment by BowenHero** [comment]
@xaboy

**Comment by guoziqin** [comment]
这里要做下判空处理

**Comment by xaboy** [comment]
已修复
